package cli

import (
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/Jacob2017/wiki-audio/internal/atomic"
)

// configTemplate is the on-disk seed for ~/.wiki-audio/config.toml
// when init scaffolds a fresh install. Comments document each
// required field so the operator can edit without re-reading the
// PLAN. Defaults from §2 are noted in comments rather than written
// out — the loader (wa-kyn.2) populates them via model.Default* and
// duplicating values here would create a drift surface.
const configTemplate = `# wiki-audio config — see github.com/Jacob2017/wiki-audio for docs.
# Run ` + "`wiki-audio doctor`" + ` after editing to verify.

[wiki]
# Absolute path to the directory containing PG essay markdown files.
# Each .md is one episode. Required.
source_dir = ""

[tts]
# ElevenLabs voice ID to render with. PLAN §10 default is Christopher
# (G17SuINrv2H9FC6nvetn). Browse api.elevenlabs.io/v1/voices for more.
voice_id = ""
voice_label = "Christopher"
# Defaults applied when omitted: model_id="eleven_flash_v2_5",
# chunk_max_chars=4000, request_timeout_s=60, retry_attempts=3,
# retry_backoff_base_s=2, output_format="mp3_44100_64".

[r2]
# Cloudflare R2 account ID and bucket name. Both required.
# Endpoint URL is derived: https://<account_id>.r2.cloudflarestorage.com
account_id = ""
bucket = ""

[feed]
# Public Worker URL that fronts the R2 bucket. Must include scheme.
# Production hosts MUST use https:// for transport security.
base_url = "https://wiki-audio.example.workers.dev"
title = "PG Essays"
description = "Paul Graham essays read aloud."
author = "Paul Graham"
owner_email = ""
# Optional: cover_image_url = "https://..."
# Defaults applied when omitted: feed_path="pg.xml", language="en-us".
`

// envTemplate is the on-disk seed for ~/.wiki-audio/.env. The token
// line is filled in by the caller via fmt.Sprintf — leaving the
// other three values intentionally empty so `wiki-audio doctor`
// surfaces missing-secrets errors that point the operator at the
// right keys to populate.
const envTemplate = `# wiki-audio secrets — chmod 600. Never check this file into git.
# Edit each empty value, then run ` + "`wiki-audio doctor`" + `.

ELEVENLABS_API_KEY=
R2_ACCESS_KEY_ID=
R2_SECRET_ACCESS_KEY=

# Generated by ` + "`wiki-audio init`" + `; mirror to 1Password and to the
# Cloudflare Worker secret ACCESS_TOKEN. Rotation: regenerate, edit
# this line, ` + "`wrangler secret put ACCESS_TOKEN`" + `, ` + "`wiki-audio publish --feed-only`" + `.
WIKI_AUDIO_ACCESS_TOKEN=%s
`

// errInitRefuse signals that init refused to overwrite an existing
// file without --force. Returned to cobra so the process exits
// non-zero.
var errInitRefuse = errors.New("init: refusing to overwrite (use --force)")

// initOpts collects the inputs runInit needs. Pulled out so tests
// can pass tempdir paths and a deterministic rand source without
// reaching into env vars.
type initOpts struct {
	configPath string
	envPath    string
	force      bool
	out        io.Writer
	rand       io.Reader // defaults to crypto/rand.Reader
}

func newInitCmd() *cobra.Command {
	var force bool
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Scaffold ~/.wiki-audio/",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfgPath, _ := cmd.Root().PersistentFlags().GetString("config")
			envPath, _ := cmd.Root().PersistentFlags().GetString("env")
			envLocal, _ := cmd.Root().PersistentFlags().GetBool("env-local")
			if envLocal {
				envPath = ".env"
			}
			return runInit(initOpts{
				configPath: cfgPath,
				envPath:    envPath,
				force:      force,
				out:        cmd.OutOrStdout(),
				rand:       rand.Reader,
			})
		},
	}
	cmd.Flags().BoolVar(&force, "force", false, "overwrite existing files")
	return cmd
}

// runInit scaffolds ~/.wiki-audio/{config.toml,.env}. Idempotent in
// the success-after-success sense: re-running on a populated install
// without --force refuses cleanly. With --force, it overwrites both
// files, regenerating the access token.
//
// Token semantics: a fresh 32-byte / 43-char URL-safe token is
// generated via crypto/rand on every fresh-create or --force. If the
// .env exists but only WIKI_AUDIO_ACCESS_TOKEN is empty (other
// secrets filled in), the token line is surgically replaced —
// preserves operator-entered API keys while completing setup. The
// generated token is printed once with mirror-to-1Password +
// wrangler-secret-put instructions.
func runInit(opts initOpts) error {
	if opts.rand == nil {
		opts.rand = rand.Reader
	}

	if err := os.MkdirAll(filepath.Dir(opts.configPath), 0o755); err != nil {
		return fmt.Errorf("init: mkdir %s: %w", filepath.Dir(opts.configPath), err)
	}
	if err := os.MkdirAll(filepath.Dir(opts.envPath), 0o755); err != nil {
		return fmt.Errorf("init: mkdir %s: %w", filepath.Dir(opts.envPath), err)
	}

	configMsg, err := writeConfigFile(opts.configPath, opts.force)
	if err != nil {
		return err
	}

	token, err := generateAccessToken(opts.rand)
	if err != nil {
		return fmt.Errorf("init: generate token: %w", err)
	}

	envMsg, tokenWritten, err := writeEnvFile(opts.envPath, opts.force, token)
	if err != nil {
		return err
	}

	fmt.Fprintln(opts.out, configMsg)
	fmt.Fprintln(opts.out, envMsg)
	fmt.Fprintln(opts.out, "next: edit config.toml and populate .env, then run `wiki-audio doctor`")

	if tokenWritten {
		fmt.Fprintln(opts.out)
		fmt.Fprintln(opts.out, "WIKI_AUDIO_ACCESS_TOKEN generated:")
		fmt.Fprintln(opts.out, "  "+token)
		fmt.Fprintln(opts.out, "Mirror this value to:")
		fmt.Fprintln(opts.out, "  - 1Password (or whatever vault you use)")
		fmt.Fprintln(opts.out, "  - Cloudflare Worker secret: wrangler secret put ACCESS_TOKEN")
	}

	return nil
}

// generateAccessToken returns the §9.1 token format: 32 random bytes,
// base64-url-encoded with no padding, yielding 43 chars matching
// [A-Za-z0-9_-]. Caller passes an io.Reader; nil defaults to
// crypto/rand.Reader. Tests inject a deterministic bytes.Reader.
func generateAccessToken(r io.Reader) (string, error) {
	if r == nil {
		r = rand.Reader
	}
	b := make([]byte, 32)
	if _, err := io.ReadFull(r, b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

// writeConfigFile writes the config template to path. If path
// already exists and force is false, returns errInitRefuse with a
// status message naming the file. Returns the human-readable status
// line on success ("created <path> (with placeholders)").
func writeConfigFile(path string, force bool) (string, error) {
	if _, err := os.Stat(path); err == nil {
		if !force {
			return "", fmt.Errorf("%w: %s already exists", errInitRefuse, path)
		}
	} else if !os.IsNotExist(err) {
		return "", fmt.Errorf("init: stat %s: %w", path, err)
	}

	if err := atomic.WriteFile(path, []byte(configTemplate), 0o644); err != nil {
		return "", fmt.Errorf("init: write %s: %w", path, err)
	}
	return fmt.Sprintf("created %s (with placeholders)", path), nil
}

// writeEnvFile writes (or surgically updates) the .env template at
// path with the given token, then chmods to 0o600. Returns:
//
//   - msg: human-readable summary line.
//   - tokenWritten: true iff the printed token was actually written
//     to disk this run (so the caller knows whether to print the
//     mirror-it instructions). False if .env exists with a non-empty
//     token line and force is false; in that case, the function
//     refused.
//   - err: errInitRefuse when refusing to overwrite, or an OS error.
func writeEnvFile(path string, force bool, token string) (string, bool, error) {
	existing, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return "", false, fmt.Errorf("init: read %s: %w", path, err)
		}
		// Fresh create.
		body := fmt.Sprintf(envTemplate, token)
		if err := writeEnvWithMode(path, []byte(body)); err != nil {
			return "", false, err
		}
		return fmt.Sprintf("created %s     (chmod 600, token generated)", path), true, nil
	}

	// File exists. Check whether the token line is filled in.
	if envHasFilledToken(string(existing)) && !force {
		return "", false, fmt.Errorf("%w: %s already exists with WIKI_AUDIO_ACCESS_TOKEN set", errInitRefuse, path)
	}

	if force {
		// Overwrite from scratch — operator explicitly asked.
		body := fmt.Sprintf(envTemplate, token)
		if err := writeEnvWithMode(path, []byte(body)); err != nil {
			return "", false, err
		}
		return fmt.Sprintf("recreated %s   (chmod 600, token regenerated)", path), true, nil
	}

	// Top-up: surgically write the token line, preserve other
	// operator-entered values.
	updated := topUpTokenLine(string(existing), token)
	if err := writeEnvWithMode(path, []byte(updated)); err != nil {
		return "", false, err
	}
	return fmt.Sprintf("updated %s     (chmod 600, token populated)", path), true, nil
}

// writeEnvWithMode writes data to path atomically with mode 0o600.
// The atomic helper chmods the temp file BEFORE Rename so the
// publish window cannot leak a 0o644 mode (umask would otherwise
// override os.WriteFile's perm), and a crash mid-write leaves any
// pre-existing .env unchanged (wa-76r.2).
func writeEnvWithMode(path string, data []byte) error {
	if err := atomic.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("init: write %s: %w", path, err)
	}
	return nil
}

// envHasFilledToken returns true iff the .env content contains a
// `WIKI_AUDIO_ACCESS_TOKEN=<non-empty>` line. Comment lines starting
// with `#` are ignored. Used to decide top-up vs refuse.
func envHasFilledToken(content string) bool {
	for _, line := range strings.Split(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") {
			continue
		}
		if !strings.HasPrefix(trimmed, "WIKI_AUDIO_ACCESS_TOKEN=") {
			continue
		}
		val := strings.TrimPrefix(trimmed, "WIKI_AUDIO_ACCESS_TOKEN=")
		if val != "" {
			return true
		}
	}
	return false
}

// topUpTokenLine returns content with the WIKI_AUDIO_ACCESS_TOKEN=
// line replaced by `WIKI_AUDIO_ACCESS_TOKEN=<token>`. If no such
// line exists, the new line is appended. Other lines (operator-
// entered API keys, comments, blank lines) are preserved verbatim.
func topUpTokenLine(content, token string) string {
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") {
			continue
		}
		if strings.HasPrefix(trimmed, "WIKI_AUDIO_ACCESS_TOKEN=") {
			lines[i] = "WIKI_AUDIO_ACCESS_TOKEN=" + token
			return strings.Join(lines, "\n")
		}
	}
	// No token line — append.
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	return content + "WIKI_AUDIO_ACCESS_TOKEN=" + token + "\n"
}
